# Generated by Django 4.0.4 on 2022-06-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_categoria_producto_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
