# Generated by Django 4.0.4 on 2022-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_remove_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
