# Generated by Django 4.0.4 on 2022-06-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_alter_categoria_producto_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria_Producto',
        ),
    ]
