# Generated by Django 4.0.4 on 2022-06-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_delete_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
    ]
