# Generated by Django 4.0.4 on 2022-06-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_animal_producto_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mascota.animal_producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mascota.categoria_producto'),
        ),
    ]
