# Generated by Django 4.0.4 on 2022-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0010_perfilusuario_delete_perfilcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
